"""Seed Handwerksgewerbe nach HwO (Anlage A, B1, B2). Safe to run multiple times (idempotent)."""
from app.database import SessionLocal
from app.models.profession import Profession

# Quelle: Handwerksordnung (HwO), gesetze-im-internet.de
PROFESSIONS = sorted([
    "Änderungsschneider",
    "Appreteure, Dekateure",
    "Asphaltierer (ohne Straßenbau)",
    "Augenoptiker",
    "Ausführung einfacher Schuhreparaturen",
    "Bäcker",
    "Bautentrocknungsgewerbe",
    "Behälter- und Apparatebauer",
    "Bestatter",
    "Betonbohrer und -schneider",
    "Bodenleger",
    "Bogenmacher",
    "Boots- und Schiffbauer",
    "Brauer und Mälzer",
    "Buchbinder",
    "Büchsenmacher",
    "Bügelanstalten für Herren-Oberbekleidung",
    "Bürsten- und Pinselmacher",
    "Chirurgiemechaniker",
    "Dachdecker",
    "Daubenhauer",
    "Dekorationsnäher (ohne Schaufensterdekoration)",
    "Drechsler (Elfenbeinschnitzer) und Holzspielzeugmacher",
    "Edelsteinschleifer und -graveure",
    "Einbau von genormten Baufertigteilen (zum Beispiel Fenster, Türen, Zargen, Regale)",
    "Eisenflechter",
    "Elektromaschinenbauer",
    "Elektrotechniker",
    "Estrichleger",
    "Fahrzeugverwerter",
    "Feinoptiker",
    "Feinwerkmechaniker",
    "Fleischer",
    "Fleischzerleger, Ausbeiner",
    "Fliesen-, Platten- und Mosaikleger",
    "Fleckteppichhersteller",
    "Fotografen",
    "Friseure",
    "Fuger (im Hochbau)",
    "Galvaniseure",
    "Gebäudereiniger",
    "Geigenbauer",
    "Gerber",
    "Gerüstbauer",
    "Getränkeleitungsreiniger",
    "Glas- und Porzellanmaler",
    "Glaser",
    "Glasbläser und Glasapparatebauer",
    "Glasveredler",
    "Gold- und Silberschmiede",
    "Graveure",
    "Handschuhmacher",
    "Handzuginstrumentenmacher",
    "Herstellung von Drahtgestellen für Dekorationszwecke in Sonderanfertigung",
    "Hörakustiker",
    "Holzblasinstrumentenmacher",
    "Holzbildhauer",
    "Holzblockmacher",
    "Holz- und Bautenschützer (Mauerschutz und Holzimprägnierung in Gebäuden)",
    "Holz-Leitermacher (Sonderanfertigung)",
    "Holzreifenmacher",
    "Holzschindelmacher",
    "Holzschuhmacher",
    "Informationstechniker",
    "Innerei-Fleischer (Kuttler)",
    "Installateur und Heizungsbauer",
    "Kabelverleger im Hochbau (ohne Anschlussarbeiten)",
    "Kälteanlagenbauer",
    "Karosserie- und Fahrzeugbauer",
    "Keramiker",
    "Klavier- und Cembalobauer",
    "Klavierstimmer",
    "Klempner",
    "Konditoren",
    "Korb- und Flechtwerkgestalter",
    "Kosmetiker",
    "Kraftfahrzeugtechniker",
    "Kürschner",
    "Kunststopfer",
    "Lampenschirmhersteller (Sonderanfertigung)",
    "Land- und Baumaschinenmechatroniker",
    "Maler und Lackierer",
    "Maskenbildner",
    "Maßschneider",
    "Maurer und Betonbauer",
    "Mechaniker für Reifen- und Vulkanisationstechnik",
    "Metall- und Glockengießer",
    "Metallbauer",
    "Metallbildner",
    "Metallblasinstrumentenmacher",
    "Metallsägen-Schärfer",
    "Metallschleifer und Metallpolierer",
    "Modellbauer",
    "Modisten",
    "Müller",
    "Muldenhauer",
    "Ofen- und Luftheizungsbauer",
    "Orgel- und Harmoniumbauer",
    "Orthopädieschuhmacher",
    "Orthopädietechniker",
    "Parkettleger",
    "Plisseebrenner",
    "Präzisionswerkzeugmechaniker",
    "Print- und Medientechnologen (Drucker, Siebdrucker, Flexografen)",
    "Rammgewerbe (Einrammen von Pfählen im Wasserbau)",
    "Raumausstatter",
    "Requisiteure",
    "Rohr- und Kanalreiniger",
    "Rollladen- und Sonnenschutztechniker",
    "Sattler und Feintäschner",
    "Schirmmacher",
    "Schilder- und Lichtreklamehersteller",
    "Schlagzeugmacher",
    "Schornsteinfeger",
    "Schnellreiniger",
    "Schuhmacher",
    "Segelmacher",
    "Seiler",
    "Speiseeishersteller (mit Vertrieb von Speiseeis mit üblichem Zubehör)",
    "Steindrucker",
    "Steinmetzen und Steinbildhauer",
    "Stoffmaler",
    "Straßenbauer",
    "Stuckateure",
    "Tankschutzbetriebe (Korrosionsschutz von Öltanks für Feuerungsanlagen ohne chemische Verfahren)",
    "Teppichreiniger",
    "Textil-Handdrucker",
    "Textilgestalter (Sticker, Weber, Klöppler, Posamentierer, Stricker)",
    "Textilreiniger",
    "Theater- und Ausstattungsmaler",
    "Theaterkostümnäher",
    "Theaterplastiker",
    "Tischler",
    "Uhrmacher",
    "Vergolder",
    "Wachszieher",
    "Wärme-, Kälte- und Schallschutzisolierer",
    "Weinküfer",
    "Werkstein- und Terrazzohersteller",
    "Zahntechniker",
    "Zimmerer",
    "Zupfinstrumentenmacher",
    "Zweiradmechaniker",
])


def seed():
    db = SessionLocal()
    try:
        count = db.query(Profession).count()
        if count == len(PROFESSIONS):
            print(f"[SEED] Professions already seeded ({count}) — skipping")
            return
        if count > 0:
            print(f"[SEED] Professions incomplete ({count}/{len(PROFESSIONS)}) — reseeding...")
            db.query(Profession).delete()
            db.commit()
        db.bulk_save_objects([Profession(name=name) for name in PROFESSIONS])
        db.commit()
        print(f"[SEED] {len(PROFESSIONS)} professions seeded.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()