"""initial schema

Revision ID: ad264ec5cd68
Revises: 
Create Date: 2026-06-12 22:57:21.589520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad264ec5cd68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('bsi_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_tag', sa.String(length=64), nullable=False),
    sa.Column('release_date', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_tag')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('mail', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('bh_always', sa.Boolean(), nullable=False),
    sa.Column('bh_weekday_start', sa.Integer(), nullable=True),
    sa.Column('bh_weekday_end', sa.Integer(), nullable=True),
    sa.Column('bh_time_start', sa.Integer(), nullable=True),
    sa.Column('bh_time_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_src', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('incident_link_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_signs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loc_countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('support_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('contact_person', sa.String(length=256), nullable=True),
    sa.Column('street', sa.String(length=256), nullable=True),
    sa.Column('street_number', sa.String(length=32), nullable=True),
    sa.Column('address_details', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('mail', sa.String(length=256), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('glossary_terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['glossary_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_keyword'), 'glossary_terms', ['keyword'], unique=False)
    op.create_table('incident_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['incident_link_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_sign_examples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sign_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sign_id'], ['incident_signs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loc_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['loc_countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bsi_version_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=32), nullable=False),
    sa.Column('parent_control_id', sa.String(length=32), nullable=True),
    sa.Column('group_id', sa.String(length=16), nullable=False),
    sa.Column('group_title', sa.String(length=128), nullable=False),
    sa.Column('subgroup_id', sa.String(length=16), nullable=False),
    sa.Column('subgroup_title', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('guidance_text', sa.Text(), nullable=True),
    sa.Column('sec_level', sa.String(length=32), nullable=False),
    sa.Column('effort_level', sa.Integer(), nullable=False),
    sa.Column('bsi_uuid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bsi_version_id'], ['bsi_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'bsi_version_id', name='uq_control_version')
    )
    op.create_table('support_offer_topics',
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['support_offers.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['support_topics.id'], ),
    sa.PrimaryKeyConstraint('offer_id', 'topic_id')
    )
    op.create_table('support_service_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['support_offers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['support_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('referenced_term_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['referenced_term_id'], ['glossary_terms.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['glossary_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['glossary_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_synonyms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['glossary_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loc_counties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['loc_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('measure_id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measure_id', name='uq_mapping_measure')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mapping_id', sa.String(length=36), nullable=False),
    sa.Column('bsi_version_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bsi_version_id'], ['bsi_versions.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['mappings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mapping_id')
    )
    op.create_table('loc_cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['loc_counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loc_cities_name'), 'loc_cities', ['name'], unique=False)
    op.create_index(op.f('ix_loc_cities_postal_code'), 'loc_cities', ['postal_code'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('size_class', sa.String(length=16), nullable=True),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['loc_cities.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=128), nullable=True),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('checklist_item_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'checklist_item_id', name='uq_progress_company_item')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('progress_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['progress_id'], ['progress.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('progress')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('companies')
    op.drop_index(op.f('ix_loc_cities_postal_code'), table_name='loc_cities')
    op.drop_index(op.f('ix_loc_cities_name'), table_name='loc_cities')
    op.drop_table('loc_cities')
    op.drop_table('checklist_items')
    op.drop_table('mappings')
    op.drop_table('loc_counties')
    op.drop_table('glossary_synonyms')
    op.drop_table('glossary_sources')
    op.drop_table('glossary_references')
    op.drop_table('support_service_entries')
    op.drop_table('support_offer_topics')
    op.drop_table('measures')
    op.drop_table('loc_states')
    op.drop_table('incident_sign_examples')
    op.drop_table('incident_links')
    op.drop_index(op.f('ix_glossary_terms_keyword'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    op.drop_table('support_topics')
    op.drop_table('support_organizations')
    op.drop_table('support_offers')
    op.drop_table('professions')
    op.drop_table('loc_countries')
    op.drop_table('incident_signs')
    op.drop_table('incident_link_categories')
    op.drop_table('glossary_categories')
    op.drop_table('emergency_contacts')
    op.drop_table('bsi_versions')
    op.drop_table('areas')
    # ### end Alembic commands ###
